before_install: gem install bundler --pre
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - buddhi@kill3rmedia.com


rvm:
  - 1.9.2
  - 1.9.3